# Generated by Django 4.2.8 on 2023-12-14 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0018_alter_exam_model_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam_model",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 15, 0, 38, 7, 576004)
            ),
        ),
        migrations.AlterField(
            model_name="exam_model",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="exam_model",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 15, 0, 38, 7, 576004)
            ),
        ),
        migrations.AlterField(
            model_name="question_paper",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
